### ISSUE TITLE
What is the license for this project?

### ISSUE THREAD

**Issue by oliverbrixel** [edreyer/modulith#21]
Thank you for this great sample project. Can you please add a license file so that it is clear in which form it can be used?

**Comment by edreyer** [comment]
Thanks @oliverbrixel 

I added the MIT license. Would love to know how you use this project. 

Cheers,
Erik

**Comment by oliverbrixel** [comment]
Thank you very much! This a very kind of you. 

I like the setup and will try to use it for one of our projects. At the moment I'm porting it to Gradle. As soon as I have something usable, I'll get back to you.

**Comment by edreyer** [comment]
Nice. Would love to see that. Every time I attempt to use gradle I end up in misery trying to get it to work. Feel free to submit a PR for that.
